version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/web
      - .env/development/database
  
  database:
    image: postgres
    env_file:
      - .env/development/database